config/routes.rb
Rails.application.routes.draw do
  
  #個人情報保護ページ
  get 'protection_low/index'
  #　レッスン関連
  get 'lessons/weeklyschedule'
  post 'lessons/create', to: 'lessons#create'
  #　ユーザー側予約詳細へ
  post 'reservationusers/useredit', to: 'reservationusers#useredit'
  get 'reservationusers/useredit', to: 'reservationusers#useredit'
  #　ユーザー側予約情報更新
  post 'reservationusers/userupdate', to: 'reservationusers#userupdate'
  get 'reservationusers/reservation_delete', to: 'reservationusers#reservation_delete'
  post 'reservationusers/reservation_change_user', to: 'reservationusers#reservation_change_user'
  post 'reservationusers/reservationnewuser', to: 'reservationusers#reservationnewuser'
  post 'reservationusers/reservation_create'
  # 授業コメント
  post 'lessoncomments/create', to: 'lessoncomments#create'
  # 問い合わせ回答
  post 'answers/create', to: 'answers#create'
  # ユーザー側生徒情報更新
  put 'basic_infos/student_update', to: 'basic_infos#student_update'
  patch 'maneger_students/update', to: 'maneger_students#update'
  #管理者　授業中止
  patch '/lessons/cancellation', to: 'lessons#cancellation'
  get 'sessions/new'
  root :to => 'notices#index'
  get '/signup', to: 'users#new'
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :reservation_logs, only: [:index]
  
  # ログインボタン(管理者、生徒)
  patch 'login', to: 'sessions#admin_login'
  put 'login', to: 'sessions#student_login'
  
  resources :users do
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'edit'
      put 'update'
    end
  end
  delete 'users/:id/delete', to: 'users#destroy'
  
  resources :lessons do
   member do
     put 'update'
     get 'lesson_detail'
     patch 'lesson_detail'
     get 'lesson_discontinuation_fix'
     patch 'lesson_discontinuation_fix'
     get 'add_student'
     patch 'add_student'
     delete 'destroy'
   end
  end
  
  resources :students do
    member do
      get 'info_edit'
      patch 'info_update'
      delete 'destroy'
      get 'create'
    end
    collection do
      post 'create'
    end
  end

  resources :notices
  
  resources :reservations, only: [:update, :destroy]
  
  resources :questions
  
  resources :password_resets, only: [:new, :create, :edit, :update]
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :answers, dependent: :destroy
  scope :created_at_order, -> { order(created_at: :desc) }
  
  validates :question_content, presence: true
  validates :question_title, presence: true
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :destroy]
  before_action :unless_question, only: :show
  before_action :logged_in_user, only: [:show, :update, :index, :destroy]
  before_action :admin_user, only: :destroy
  before_action :mail_link_host,   only: [:create]

  
  def index
    if current_user.admin?
      @questions = Question.paginate(page: params[:page], per_page: 10).created_at_order
    else
      @questions = Question.where("user_id =? or destination =?", current_user.id, current_user.id).paginate(page: params[:page], per_page: 10).created_at_order
    end
  end
  
  def show
    question_id = params[:id]
    @answers = Answer.where("question_id = ?" , question_id)
    @student = Student.find(@question.student_id) if @question.student_id.present?
    @user_guargian = User.find(@question.destination).guardian
  end
  
  def new
    @question = Question.new
    @users = User.undercontract.where.not(id:current_user.id)
  end
  
  def create
    @question = Question.new(question_params)
    # ログインしているidが反映させる↓
    @question.user_id = current_user.id
    if @question.save
      @title = "お問い合わせの登録がありました"
      @content = "お問い合わせの登録がありました。"
      send_mail_address
      flash[:success] = "登録に成功し、通知メールを送信しました"
      redirect_to questions_url
    else
      render :new
    end
  end
  
  def destroy
    @question.destroy
    flash[:success] = "タイトル名「#{@question.question_title}」を削除しました。"
    redirect_to questions_url
  end
  
   private
   
    def question_params
      params.require(:question).permit(:question_title, :question_content, :destination, :student_id)
    end
    
    def set_question
      @question = Question.find(params[:id])
    end
    
    def unless_question
      @question = Question.find(params[:id])
      unless current_user.admin? or @question.user.id == current_user.id or @question.destination == current_user.id
        redirect_to questions_url
      end 
    end
    
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "ログインしてください。"
        redirect_to login_url
      end
    end
    
    # システム管理権限所有かどうか判定します。
    def admin_user
      redirect_to root_url unless current_user.admin?
    end

    def send_mail_address
      if current_user.admin?
        @destination_user = User.find( @question.destination )
        @bcc = current_user.email
      else
        @destination_user = User.find(1)
        @bcc = ""
      end
      @send_user =  current_user
      link = "questions"
      @link = @url + link
      UserMailer.send_mail( @destination_user, @send_user, @bcc, @title, @content,@link).deliver_now
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/index.html.erb
<% provide(:title, '問い合わせ一覧') %>

<div class="wrapper_normal2">
  <h1 id="index">問い合わせ一覧</h1>
  <div class="button-area" style="text-align: center; margin-bottom:20px;">
    <%= link_to "問い合わせ投稿", new_question_path, class: "btn btn-primary question-btn" %>
  <div class="ol-md-12 col-md-offset-0">
    <% if @questions.present? %>
      <div class="question-paginate"><%= will_paginate %></div>
      <table class="table table-bordered table-condensed" id="table-question" style="table-layout:fixed;">
        <thead>
          <tr>
            <th colspan="2">投稿日</th>
            <th colspan="2">投稿者</th>
            <th colspan="2">送信先</th>
            <th colspan="3"><div style="white-space:nowrap;">タイトル</div></th>
            <th colspan="1"><div style="white-space:nowrap;">コメント</div></th>
            <% if current_user.admin? %>
              <th colspan="1">投稿削除</th>
            <% end %>
          </tr> 
        </thead>
        <thead>
          <% @questions.each do |question| %>
            <tr id="question-<%= question.id %>">
              <td colspan="2" style="word-wrap:keep-all;"><%= l(question.updated_at, format: :default_2) %></td>
              <td colspan="2"><div style="white-space:nowrap;"><%= question.user.guardian %></div></td>
              <td colspan="2"><div style="white-space:nowrap;"><%= User.find(question.destination).guardian %></div></td>
              <td colspan="3" style="word-wrap:break-word;"><%= link_to question.question_title, question %></td>
              <td colspan="1" style="word-wrap:break-word;"><%=question.answers.count %></td>
              <% if current_user.admin? %>
              <td colspan="1">
                  <%= link_to "削除", question, method: :delete, data: { confirm: "削除してよろしいですか？" }, class: "btn btn-danger btn-sm" %>
              </td>
              <% end %>
            </tr>
          <% end %>
        </thead>
      </table>
    <% else %>
      <p class="question-index">問い合わせはありません</p>
    <% end %>
</div>

app/views/questions/new.html.erb
<% provide(:title, '問い合わせ') %>
<% provide(:class_text, 'signup') %>
<% provide(:button_text, '送信') %>
<h1>問い合わせ</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @question, local: true) do |f| %>
      <%= render 'shared/error_messages_question' %>
      
      <% if current_user.admin %>
        <%= f.label :destination, "送信先", class: "label-#{yield(:class_text)}" %>
        <span class="label label-danger label-user-division">必須</span>
        <%= f.collection_select :destination, @users, :id, :guardian, {}, required: true, class: "form-control" %>
      <% else %>
        <%= f.hidden_field :destination, value: 1 %>
      <% end %>
      
      <%= f.label :student_id, "生徒名", class: "label-#{yield(:class_text)}" %>
      <% if current_user.admin %>
        <%= f.collection_select :student_id, Student.kanaorder, :id, :student_name, {include_blank: true}, class: "form-control" %>
      <% else %>
        <%= f.collection_select :student_id, Student.kanaorder.where("user_id = ?", current_user.id), :id, :student_name, {include_blank: true}, class: "form-control" %>
      <% end %>
    
      <%= f.label :question_title, "タイトル", class: "label-#{yield(:class_text)}" %>
      <span class="label label-danger label-user-division">必須</span>
      <%= f.text_field :question_title, required: true, class: "form-control" %>
      
      <%= f.label :question_content, "内容", class: "label-#{yield(:class_text)}" %>
      <span class="label label-danger label-user-division">必須</span>
      <%= f.text_area :question_content, required: true, class: "form-control", rows: 5 %>
      
      <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
      
    <% end %>
  </div>
</div>
<br>
<div style="text-align:center"><%= link_to "問い合わせ一覧に戻る", questions_path %></div>

app/views/questions/show.html.erb
<% provide(:title, '問い合わせ詳細') %>

<h1>問い合わせ詳細</h1>

<div class="wrapper_normal">
  <div class="box17" id="questions-info-show" style="table-layout:fixed;width:100%; ">
    <!--タイトル-->
    <div class="question-title" style="word-wrap:break-word;"><%= @question.question_title %></div>
    <!--投稿日時-->
    <div><%= l(@question.created_at, format: :default_2) %></div>
    <!--宛先-->
    <div class="question-destination">宛先：<%= @user_guargian %></div>
    <!--投稿者-->
    <div class="question-destination">
      投稿者：<%= @question.user.guardian %>
      <span>
        生徒名：<% if @question.student_id.present? %>
                  <%= @student.student_name %>
                <% else %>
                  対象なし
                <% end %>
      </span>
    </div>
    <!--内容-->
    <div class="question-content" style="word-wrap:break-word;"><%= simple_format @question.question_content %></div>
  </div>
    
  <div style="text-align:center;">〜 返信  〜</div><br>
  <%= form_with(model:@answer, url: answers_create_path,local: true) do |f| %>
    <%= f.hidden_field:question_id, value:@question.id %>
    <%= f.hidden_field:user_id, value: current_user.id %>
    <%= f.text_area :answer_content, class: "form-control answer_form", required:true, rows: 4 %><br />
    <div class="answer-btn-1"><%= f.submit value:"返信", class:"btn-sm btn-primary answer-btn-2" %></div>
  <% end %>
    
  <% if @answers.present? %>
    <div style="text-align:center;">〜 返信一覧 〜</div>
    <div class="answer_table">
      <% @answers.each do |comment| %>
        <!--文が長い場合は改行させる-->
        <div class="box17" style="word-wrap:break-word;">
          <div class="answer_left question-destination">
            <% if comment.user.admin == false %>
              <%= comment.user.guardian %>
              <br>
            <% else %>
              <%= comment.user.guardian %>
              <br>
            <% end %>
            </div>
            <div class="answer_right"><%= l(comment.updated_at, format: :default_2) %></div>
            <br>
            <div class="question-destination"><%= simple_format comment.answer_content %></div>
          </div>
      <% end %>
    </div>
  <% end %>
  <div style="text-align:center; margin-top:10px;"><%= link_to "問い合わせ一覧に戻る", questions_path %></div>
</div>