config/routes.rb
Rails.application.routes.draw do
  
  #個人情報保護ページ
  get 'protection_low/index'
  #　レッスン関連
  get 'lessons/weeklyschedule'
  post 'lessons/create', to: 'lessons#create'
  #　ユーザー側予約詳細へ
  post 'reservationusers/useredit', to: 'reservationusers#useredit'
  get 'reservationusers/useredit', to: 'reservationusers#useredit'
  #　ユーザー側予約情報更新
  post 'reservationusers/userupdate', to: 'reservationusers#userupdate'
  get 'reservationusers/reservation_delete', to: 'reservationusers#reservation_delete'
  post 'reservationusers/reservation_change_user', to: 'reservationusers#reservation_change_user'
  post 'reservationusers/reservationnewuser', to: 'reservationusers#reservationnewuser'
  post 'reservationusers/reservation_create'
  # 授業コメント
  post 'lessoncomments/create', to: 'lessoncomments#create'
  # 問い合わせ回答
  post 'answers/create', to: 'answers#create'
  # ユーザー側生徒情報更新
  put 'basic_infos/student_update', to: 'basic_infos#student_update'
  patch 'maneger_students/update', to: 'maneger_students#update'
  #管理者　授業中止
  patch '/lessons/cancellation', to: 'lessons#cancellation'
  get 'sessions/new'
  root :to => 'notices#index'
  get '/signup', to: 'users#new'
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :reservation_logs, only: [:index]
  
  # ログインボタン(管理者、生徒)
  patch 'login', to: 'sessions#admin_login'
  put 'login', to: 'sessions#student_login'
  
  resources :users do
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'edit'
      put 'update'
    end
  end
  delete 'users/:id/delete', to: 'users#destroy'
  
  resources :lessons do
   member do
     put 'update'
     get 'lesson_detail'
     patch 'lesson_detail'
     get 'lesson_discontinuation_fix'
     patch 'lesson_discontinuation_fix'
     get 'add_student'
     patch 'add_student'
     delete 'destroy'
   end
  end
  
  resources :students do
    member do
      get 'info_edit'
      patch 'info_update'
      delete 'destroy'
      get 'create'
    end
    collection do
      post 'create'
    end
  end

  resources :notices
  
  resources :reservations, only: [:update, :destroy]
  
  resources :questions
  
  resources :password_resets, only: [:new, :create, :edit, :update]
end

app/models/notice.rb
class Notice < ApplicationRecord
  belongs_to :user
  default_scope -> { order(updated_at: :desc) }
  validates :notice_title,  presence: true
  validates :notice_content, presence: true
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  before_action :set_notice, only: %i(edit show update destroy)
  before_action :set_student
  before_action :unless_login
  before_action :day_setting, only: %i(index)
  before_action :admin_user, only: %i(new edit)
  before_action :mail_link_host,   only: [:create]
  
  def index
    @notices = Notice.paginate(page: params[:page], per_page: 10)
    @reservations = Reservation.joins(:lesson).where('lessons.meeting_on >=? and reservations.user_id=?',@today,current_user.id).order(meeting_on: "ASC") .order(fix_time: "ASC")
    @students = Student.where("user_id = ?",current_user.id).where(withdrawal: nil)
  end
  
  def new
    @notice = Notice.new
  end
  
  def edit
  end
  
  def create
    @notice = Notice.new(notice_params)
    @notice.user_id=current_user.id
    if @notice.save
      flash[:success] = "タイトル名「#{@notice.notice_title}」を作成し、契約中の保護者全員にお知らせメールを送りました"
      title = "タイトル名「#{@notice.notice_title}」を作成しました。"
      content = "お知らせ情報を追加しました。下記を参照下さい。"
      link = "notices"
      @link = @url + link
      User.sendmail_all_users( title, content, @link )
      redirect_to notices_url
    else
      render :new
    end
  end
  
  def show
  end
  
  def update
    if @notice.update_attributes(notice_params)
      flash[:success] = "お知らせ情報を更新しました。"
      redirect_to notices_url
    else
      render :edit
    end
  end
  
  def destroy
    @notice.destroy
    flash[:success] = "タイトル名「#{@notice.notice_title}」のデータを削除しました。"
    redirect_to notices_url
  end
  
  private
    
    def notice_params
      params.require(:notice).permit(:notice_title, :notice_content)
    end
    
    def set_notice
      @notice = Notice.find(params[:id])
    end
end

app/helpers/notices_helper.rb
module NoticesHelper
    
  # 一時的セッションにいるユーザーを返す。
  # 現在ログインしているユーザーがいる場合オブジェを返す。
  
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end
  
end

app/views/notices/_basicstudent.html.erb
<!-- 2.編集モーダルの配置 -->
<div class="modal fade" id="modal-sa" tabindex="-1" style="font-size: 20px;">
  <div class="modal-dialog modal-xl">
    <!-- 3.モーダルのコンテンツ -->
    <div class="modal-content">
      <!-- 4.モーダルのヘッダ -->
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">
            <span aria-hidden="true">&times;</span>
          </button>
        <h2 class="modal-title" id="modal-label"><b>基本情報閲覧・学校名編集</b></h2>

        <div class="modal-body">

          <%= form_with(model:@artile,url: basic_infos_student_update_path, method: :put, local: true) do |f| %>
            <% @students.each do |student| %>
              <%= fields_for "studentsmany[]",student do |st| %>
                <table class="table-student">
                  <tr>
                    <th>生徒名</th>
                    <td>
                      <%= student.student_name %>
                    </td>
                  </tr>
                  <tr>
                    <th>生年月日</th>
                    <td>
                      <%= student.birthday.year %>年<%= daydis(student.birthday) %>
                    </td>
                  </tr>
                  <tr>
                    <th>固定時間</th>
                    <td>
                      <%= student.fix_day %>曜日
                      <%= timedisplay(student.fix_time) %>～<%= timedisplay(student.fix_finishtime) %>
                    </td>
                  </tr>
                  <% if student.fix_day2.present? and student.fix_time2.present? %>
                    <tr>
                      <th>固定時間2</th>
                      <td>
                        <%= student.fix_day2 %>曜日
                        <%= timedisplay(student.fix_time2) %>～<%= timedisplay(student.fix_finishtime2) %>
                      </td>
                    </tr>
                    <% end %>
                      <% if student.fix_day3.present? and student.fix_time3.present? %>
                        <tr>
                          <th>固定時間3</th>
                          <td>
                            <%= student.fix_day3 %>曜日
                            <%= timedisplay(student.fix_time3) %>～<%= timedisplay(student.fix_finishtime3) %>
                          </td>
                        </tr>
                        <% end %>
                        <% if student.fix_day4.present? and student.fix_time4.present? %>
                        <tr>
                          <th>固定時間4</th>
                          <td>
                            <%= student.fix_day4 %>曜日
                            <%= timedisplay(student.fix_time4) %>～<%= timedisplay(student.fix_finishtime4) %>
                          </td>
                        </tr>
                        <% end %>
                        <% if student.fix_day5.present? and student.fix_time5.present? %>
                        <tr>
                          <th>固定時間5</th>
                          <td>
                            <%= student.fix_day5 %>曜日
                            <%= timedisplay(student.fix_time5) %>～<%= timedisplay(student.fix_finishtime5) %>
                          </td>
                        </tr>
                        <% end %>
                          <tr>
                            <th>学校名</th>
                            <td>
                              <%= st.text_field :school ,  style: "width:200px", required: true %>
                            </td>
                          </tr>
                          <tr>
                            <th>学年</th>
                            <td>
                              <%= Student.gradeyear(student.id) %>
                            </td>
                          </tr>
                          <tr>
                            <th>授業方法</th>
                            <td>
                              <%= attend(student.zoom) %>
                            </td>
                          </tr>
                          <tr>
                            <th>受験区分</th>
                            <td>
                              <%= tasker(student.examinee) %>
                            </td>
                          </tr>
                </table> <br />
                <% end %>
              <% end %>
            <div class="modal-footer">
              <%= submit_tag value="更新", :class => "btn btn-primary", data: { confirm: "更新していいですか"} %>&nbsp;
              <button type="button" class="btn btn-default" data-dismiss="modal">閉じる</button>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/notices/_notice_form.html.erb
<%= form_with(model: @notice, local: true) do |f| %>
  <%= render 'shared/error_messages_notice' %>

  <%= f.label :notice_title, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :notice_title, class: "form-control" %>
  
  <%= f.label :notice_content, class: "label-#{yield(:class_text)}" %>
  <%= f.text_area :notice_content, class: "form-control", rows: 10 %>
  
  <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %><br />
  <p style="text-align:center"><a href="#" onclick="javascript:window.history.back(-1);return false;">詳細に戻る</a></p>
  <br />
  <% if current_user.admin? %>
    <p style="text-align:center"><a href="http://titonet384.sakura.ne.jp/linkmake/"  target="_blank">リンクはこちらでタグ作成して貼り付けて下さい</a></p>
  <% end %>
<% end %>

app/views/notices/edit.html.erb
<% provide(:title, 'お知らせ詳細') %>
<% provide(:class_text, 'signup') %>
<% provide(:button_text, 'お知らせ投稿編集') %>
<h1>お知らせ詳細</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'notice_form' %>
  </div>
</div>

app/views/notices/index.html.erb
<% provide(:title, 'お知らせ一覧') %>
<% require 'date' %>
<% today=Date.today %>
<div class="wrapper_normal">
<h1>平川塾からのお知らせ</h1>
  <div class="add-notice-information-btn">
    <% if current_user.admin? %>
    <%= link_to "お知らせ投稿", new_notice_path, class: "btn btn-primary" %>
    <% end %>
  </div>
  <% if @notices.present? %>
  <table class="table-bordered table-condensed" id="notices-info">
    <thead>
      <tr>
        <th>送信日時</th>
        <th>タイトル</th>
      </tr>
    </thead>
    <thead>
      <% @notices.each do |notice| %>
      <tr>
        <td><%= l(notice.updated_at, format: :day_time) %></td>
        <td>
          <%= link_to notice.notice_title, notice %>
          <% if current_user.admin? %>
          <%= link_to "削除", notice, method: :delete,
            data: { confirm: "削除してよろしいですか？" },
            class: "btn btn-danger btn-sm pull-right" %>
          <% end %>
        </td>
      </tr>
      <% end %>
    </thead>
  </table>
  <% else %>
    <h2>投稿はありません</h2>
  <% end %>
  <% if will_paginate.blank? %>
    <br>
  <% else %>
  <div style = "margin : -20px 0 -20px 0" >
      <%= will_paginate %>
  </div>
  <% end %>
  <div class="panel panel-info">
    <div class="panel-heading">
      <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>
      &nbsp;<%= link_to "スケジュールへのリンク", lessons_weeklyschedule_path %>
    </div>
  </div>
    <% if @reservations.present? %>
    <div class="bg-warning">
    <div class="panel-heading" data-toggle="collapse" data-target="#demo">
      <span class="glyphicon glyphicon-envelope" aria-hidden="true"> 予約授業確認・予約授業へのコメント（遅刻等の連絡、クリックで展開）</div></span>
    <div id="demo" class="collapse">
      <% @reservations.each do |reservation| %>
      <br>
      <P>・<%= link_to l(reservation.lesson.meeting_on.to_datetime, format: :day_week),"/reservationusers/useredit?lesson_id=#{reservation.lesson.id}&student_id=#{reservation.student.id}" %>
      <%= l(reservation.lesson.started_at, format: :time) %>～<%= l(reservation.lesson.finished_at, format: :time) %>
      <% if reservation.fix_time.present? %>
        固定時間:<%= l( reservation.fix_time, format: :time, default: '' ) %>～<%= l( reservation.fix_finishtime, format: :time, default: '' ) %>&nbsp;&nbsp;
      <% else %>
        固定時間:未設定
      <% end %>
      <%= reservation.student.student_name %>&nbsp;&nbsp;
      <% comment_count = Lessoncomment.where("lesson_id =? and student_id =?", reservation.lesson_id, reservation.student_id).count %>
      <%= "【コメント:#{ comment_count }】" if comment_count >0 %>
      <%= log_personal_cancel(reservation.cancel) %>
           <%= log_waiting(reservation.waiting) %>
           <%= log_transfer(reservation.transfer) %>
           <%= log_absence(reservation.absence) %>
           <%= log_cancel(Lesson.find(reservation.lesson_id).cancel) %>
      </P>
      <% end %>
    </div>
  </div>
  <% end %>
  <br>

  
  <!-- 2.編集モーダルの配置 -->
<% if @students.present? %>
<div class="panel panel-success">
    <div class="panel-heading">
      <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
      &nbsp;<a href="" data-toggle="modal" data-target="#modal-sa" %>
        基本情報(確認用）</a>
    </div>
  </div>
<% end %>
 <!--基本情報モーダル -->
<%= render partial: "basicstudent" %>
<!--基本情報モーダル終了 -->
</div>

app/views/notices/new.html.erb
<% provide(:title, 'お知らせ情報投稿') %>
<% provide(:class_text, 'signup') %>
<% provide(:button_text, 'お知らせ投稿') %>
<h1>お知らせ情報登録</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'notice_form' %>
  </div>
</div>

app/views/notices/show.html.erb
<% provide(:title, 'お知らせ詳細') %>

<h1>お知らせ詳細</h1>
<div class="wrapper_normal">
<div class="col-md-13 col-md-offset-0">
  <div class="add-notice-information-btn">
    <% if current_user.admin? %>
    <P style="text-align: center">
      <%= link_to "お知らせ投稿", new_notice_path, class: "btn btn-primary" %>&nbsp;
      <%= link_to "お知らせ編集", edit_notice_path(@notice.id), class: "btn btn-primary" %>
    </P>
    <% end %>
  </div>
  <div class="box17">
       <div class="notice-title"><%= @notice.notice_title %></div>
    <thead>
      <tr>
        <td colspan="4"><%= l(@notice.updated_at, format: :day_time) %></td>
      </tr>
    </thead>
    <br><br>
    <thead>
      <tr>
        <td colspan="4"><div class="notice-content"><%= simple_format @notice.notice_content %></div></td>
      </tr>
    </thead>
  </div>
  <p style="text-align:center"><a href="#" onclick="javascript:window.history.back(-1);return false;">一覧に戻る</a></div></p>
  
</div>
</div>