config/routes.rb
Rails.application.routes.draw do
  
  #個人情報保護ページ
  get 'protection_low/index'
  #　レッスン関連
  get 'lessons/weeklyschedule'
  post 'lessons/create', to: 'lessons#create'
  #　ユーザー側予約詳細へ
  post 'reservationusers/useredit', to: 'reservationusers#useredit'
  get 'reservationusers/useredit', to: 'reservationusers#useredit'
  #　ユーザー側予約情報更新
  post 'reservationusers/userupdate', to: 'reservationusers#userupdate'
  get 'reservationusers/reservation_delete', to: 'reservationusers#reservation_delete'
  post 'reservationusers/reservation_change_user', to: 'reservationusers#reservation_change_user'
  post 'reservationusers/reservationnewuser', to: 'reservationusers#reservationnewuser'
  post 'reservationusers/reservation_create'
  # 授業コメント
  post 'lessoncomments/create', to: 'lessoncomments#create'
  # 問い合わせ回答
  post 'answers/create', to: 'answers#create'
  # ユーザー側生徒情報更新
  put 'basic_infos/student_update', to: 'basic_infos#student_update'
  patch 'maneger_students/update', to: 'maneger_students#update'
  #管理者　授業中止
  patch '/lessons/cancellation', to: 'lessons#cancellation'
  get 'sessions/new'
  root :to => 'notices#index'
  get '/signup', to: 'users#new'
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :reservation_logs, only: [:index]
  
  # ログインボタン(管理者、生徒)
  patch 'login', to: 'sessions#admin_login'
  put 'login', to: 'sessions#student_login'
  
  resources :users do
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'edit'
      put 'update'
    end
  end
  delete 'users/:id/delete', to: 'users#destroy'
  
  resources :lessons do
   member do
     put 'update'
     get 'lesson_detail'
     patch 'lesson_detail'
     get 'lesson_discontinuation_fix'
     patch 'lesson_discontinuation_fix'
     get 'add_student'
     patch 'add_student'
     delete 'destroy'
   end
  end
  
  resources :students do
    member do
      get 'info_edit'
      patch 'info_update'
      delete 'destroy'
      get 'create'
    end
    collection do
      post 'create'
    end
  end

  resources :notices
  
  resources :reservations, only: [:update, :destroy]
  
  resources :questions
  
  resources :password_resets, only: [:new, :create, :edit, :update]
end

app/models/student.rb
class Student < ApplicationRecord
   belongs_to :user
   require 'date'
   validates :birthday,  presence: true
   validates :student_name,  presence: true
   validates :school,  presence: true
   has_many :reservations, dependent: :destroy
   has_many :lessoncomments, dependent: :destroy
   attr_accessor :lesson_id
   attr_accessor :lesson_note
   scope :kanaorder , -> { where(withdrawal:nil).order(studentkana: :asc)}
   
   def self.under_contact #カナ順
    nowtime = Time.new
    today = nowtime.to_date
    where("withdrawal is null").order(studentkana: "ASC")
   end

   def self.under_contact_createorder #入会順
    nowtime = Time.new
    today = nowtime.to_date
    where("withdrawal is null", today).order(created_at: "ASC")
   end

   def self.gradeyear(id)
    born=Student.find(id).birthday
    bornmonth=born.month
    bornday=born.day
    byear=born.year
    byear=byear-1 if bornmonth<=3 || (bornmonth==4 && bornday==1)
    nowmonth=Date.today.month
    nyear=Date.today.year
    nyear=Date.today.year-1 if nowmonth<=3
    grade=nyear-byear-6
    if grade<=6 && grade>0
      @grade="小#{(grade)}"
    elsif grade<=9 
      @grade="中#{(grade-6)}"
    elsif  grade<=12 
      @grade="高#{(grade-9)}"
    else
      @grade="対象外"
    end
   end
    
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :select_student, only: [:info_edit, :update_basic_info, :info_update]
  before_action :logged_in_user, only: [:show, :info_edit, :info_update]
  before_action :day_setting, only: [:info_update]
  before_action :mail_link_host,   only: [:create]
  before_action :fix_check,   only: [:info_update,:create]
  
  def show
    @students = Student.all
  end
  
  def info_edit
  end
  
  def info_update
    if @fix_check == 1
      flash[:danger] = "#{@student.student_name}の入力に不備あり、更新は失敗しました。終了時間は必須になりました。"
    elsif @student.update_attributes(student_params)
        user = User.find( @student.user_id )
        students = Student.where(user_id:@student.user_id)
      if students.where(withdrawal:nil).blank? and students.present?
        user.withdrawal = students.maximum(:withdrawal)
      else
        user.withdrawal = nil
      end
      user.save
      flash[:success] = "#{@student.student_name}の基本情報を更新しました。"
    else
      flash[:danger] = "#{@student.student_name}の入力に不備あり、更新は失敗しました。再度更新願います。" 
    end
    redirect_to users_url
  end

  def create
     @student = Student.new(student_params)
     if @fix_check == 1
       flash[:danger] = "固定時間の入力に不正あり登録に失敗しました。終了時間は必須になりました。"
     elsif @student.save
       @title = "受講者を登録しました。"
       @content = "トップページの 基本情報(確認用）を確認願います。"
       send_mail_address
       flash[:success] = "登録して対象者にメールを送信しました"
     else
       flash[:danger] = "入力に不正あり登録に失敗しました。"
     end
    redirect_to users_url
  end

  def destroy
    student = Student.find(params[:id])
    questions = Question.where("student_id =?" ,student.id)
    questions.each do |quetion|
      quetion.destroy
    end
    if student.destroy
      flash[:success] = "データを削除しました。"
    else
      flash[:danger] = "データを削除に失敗しました。"
    end
    redirect_to users_url
  end
  
  private
    def student_params
      params.require(:student).permit(:student_name, :user_id, :studentkana,  :zoom, :examinee, :school,  :birthday, :fix_day, :fix_time, :fix_finishtime, :fix_day2, :fix_time2, :fix_finishtime2, :fix_day3, :fix_time3, :fix_finishtime3, :fix_day4, :fix_time4, :fix_finishtime4, :fix_day5, :fix_time5, :fix_finishtime5, :note, :withdrawal)
    end
  
  # ログイン済みのユーザーか確認します。
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "ログインしてください。"
        redirect_to login_url
      end
    end

    def send_mail_address
      @destination_user = User.find( @student.user_id )
      @bcc = current_user.email
      @send_user =  current_user
      link = "notices"
      @link = @url + link
      UserMailer.send_mail( @destination_user, @send_user, @bcc, @title, @content,@link).deliver_now
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_info_edit.erb
<% provide(:class_text, 'info-edit') %>
<% provide(:button_text, '更新') %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <h1 class="modal-title">基本生徒情報 編集</h1>
    </div>
    <div class="modal-body">
  
          <%= form_with(model: @student, url: info_update_student_path(@student), local: true, method: :patch, id: "student_edit_form") do |f| %>
            <table class="table-student">
              <tr>
                <th>生徒名</th>
                <td><%= f.text_field :student_name , class: "form-control", required: true %></td>
              </tr>
              <tr>
                <th>生徒カナ</th>
                <td><%= f.text_field :studentkana , class: "form-control", required: true %></td>
              </tr>
              <tr>
                <th>生年月日</th>
                <td><%= f.date_field :birthday, class: "form-control", required: true %></td>
              </tr>
              <tr>
                <th>学校名</th>
                <td><%= f.text_field :school, class: "form-control" , required: true%></td>
              </tr>
              <tr>
                <th>受講方法</th>
                <td style = "text-align:left; font-size:15px; margin-left:10px;">
                &nbsp;<%= f.radio_button :zoom, :false %>&nbsp;リアル
                <%= f.radio_button :zoom, :true  %>&nbsp;Zoom</td>
              </tr>
              <tr>
                <th>受験生区分</th>
                <td style = "text-align:left; font-size:15px; margin-left:10px;">
                &nbsp;<%= f.radio_button :examinee, :true %>&nbsp;受験生
                <%= f.radio_button :examinee, :false  %>&nbsp;一般</td>
              </tr>
              <tr>
                <th>固定曜日</th>
                <% weekday = [["月"],["火"],["水"],["木"],["金"],["土"],["日"]] %>
                <td><%= f.select :fix_day, weekday, {selected:@student.fix_day}, required: true, class: "form-control new-form" %></td>
              </tr>
              <tr>
                <th>固定開始時間</th>
                <td><%= f.time_field :fix_time , class: "form-control", required: true %></td>
              </tr>
              <tr>
                <th>固定終了時間</th>
                <td><%= f.time_field :fix_finishtime , class: "form-control", required: true %></td>
              </tr>
              
              <tr>
                <th>固定曜日2</th>
                <td><%= f.select :fix_day2, weekday, {selected:@student.fix_day2,include_blank: true}, class: "form-control new-form" %></td>
              </tr>
              <tr>
                <th>固定開始時間2</th>
                <td><%= f.time_field :fix_time2 , class: "form-control" %></td>
              </tr>
              <tr>
                <th>固定終了時間2</th>
                <td><%= f.time_field :fix_finishtime2 , class: "form-control" %></td>
              </tr>
              
              <tr>
                <th>固定曜日3</th>
                <td><%= f.select :fix_day3, weekday, {selected:@student.fix_day3,include_blank: true}, class: "form-control new-form" %></td>
              </tr>
              <tr>
                <th>固定開始時間3</th>
                <td><%= f.time_field :fix_time3 , class: "form-control" %></td>
              </tr>
              <tr>
                <th>固定終了時間3</th>
                <td><%= f.time_field :fix_finishtime3 , class: "form-control" %></td>
              </tr>
              
               <tr>
                <th>固定曜日4</th>
                <td><%= f.select :fix_day4, weekday, {selected:@student.fix_day4,include_blank: true}, class: "form-control new-form" %></td>
              </tr>
              <tr>
                <th>固定開始時間4</th>
                <td><%= f.time_field :fix_time4 , class: "form-control" %></td>
              </tr>
              <tr>
                <th>固定終了時間4</th>
                <td><%= f.time_field :fix_finishtime4 , class: "form-control" %></td>
              </tr>
              
              <tr>
                <th>固定曜日5</th>
                <td><%= f.select :fix_day5, weekday, {selected:@student.fix_day5,include_blank: true}, class: "form-control new-form" %></td>
              </tr>
              <tr>
                <th>固定開始時間5</th>
                <td><%= f.time_field :fix_time5 , class: "form-control" %></td>
              </tr>
              <tr>
                <th>固定終了時間5</th>
                <td><%= f.time_field :fix_finishtime5 , class: "form-control" %></td>
              </tr>
              
              <tr>
                <th>備考</th>
                <td><%= f.text_field :note, class: "form-control" %></td>
              </tr>
              <tr>
                <th>退会日</th>
                <td><%= f.date_field :withdrawal, class: "form-control" %></td>
              </tr>
              </table>
            <div class="center">
              <%= f.submit "編集", class: "btn btn-primary" %>
              <button type="button" class="btn btn-default btn-<%= yield(:class_text) %>" data-dismiss="modal">
                キャンセル
              </button>
              <%= link_to "削除", student_path, method: :delete, 
              data:  { confirm: "本当に削除してよろしいですか？"},
              class: "btn btn-danger btn-sm" %>
            </div>
             <div id="parent"></div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
$("#student_edit_form").submit('turbolinks:request-start', function() {
  var fix = $("input[name='student[fix_time]']").val();
  var fixfinish = $("input[name='student[fix_finishtime]']").val();
  var fix2 = $("input[name='student[fix_time2]']").val();
  var fixfinish2 = $("input[name='student[fix_finishtime2]']").val();
  var fix3 = $("input[name='student[fix_time3]']").val();
  var fixfinish3 = $("input[name='student[fix_finishtime3]']").val();
  var fix4 = $("input[name='student[fix_time4]']").val();
  var fixfinish4 = $("input[name='student[fix_finishtime4]']").val();
  var fix5 = $("input[name='student[fix_time5]']").val();
  var fixfinish5 = $("input[name='student[fix_finishtime5]']").val();
  if (fix > fixfinish) {
    $("#parent").text("固定時間の入力に誤りがあります。確認して再登録お願いします。");
    return false;
  }else if (fix2 > fixfinish2) {
    $("#parent").text("固定時間2の入力に誤りがあります。確認して再登録お願いします。");
    return false;
  }else if (fix3 > fixfinish3) {
    $("#parent").text("固定時間3の入力に誤りがあります。確認して再登録お願いします。");
    return false;
  }else if (fix4 > fixfinish4) {
    $("#parent").text("固定時間4の入力に誤りがあります。確認して再登録お願いします。");
    return false;
  }else if (fix5 > fixfinish5) {
    $("#parent").text("固定時間5の入力に誤りがあります。確認して再登録お願いします。");
    return false;
  } else {
    $("#student_new_form").submit();
  }
});
</script>

app/views/students/_new_basic_info.html.erb
<div class="modal fade" id=<%= @user_id %> tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content" margin:auto;"=" margin:auto;""="margin:auto;""">
      <div class="modal-body">
      <h2>受講生新規登録</h2>
      保護者：<%= User.find(@user_id).guardian %>
      <% @student = Student.new %>
       <%= form_with(model: @student, url: students_path, local: true, method: :post, id: "student_new_form") do |f| %>
            <table class="table-student">
            <%= f.hidden_field :user_id ,value: @user_id %>
              <tr>
                <th>生徒名</th>
                <td><%= f.text_field :student_name , class: "form-control", required: true %></td>
              </tr>
              <tr>
                <th>生徒カナ</th>
                <td><%= f.text_field :studentkana ,  class: "form-control", required: true %></td>
              </tr>
              <tr>
                <th>生年月日</th>
                <td><%= f.date_field :birthday, class: "form-control", required: true %></td>
              </tr>
              <tr>
                <th>学校名</th>
                <td><%= f.text_field :school, class: "form-control", required: true %></td>
              </tr>
              <tr>
                <th>受講方法</th>
                <td style = "text-align:left; font-size:15px; margin-left:10px;">
                &nbsp;<%= f.radio_button :zoom, :false %>&nbsp;リアル
                <%= f.radio_button :zoom, :true  %>&nbsp;Zoom</td>
              </tr>
              <tr>
                <th>受験生区分</th>
                <td style = "text-align:left; font-size:15px; margin-left:10px;">
                &nbsp;<%= f.radio_button :examinee, :true %>&nbsp;受験生
                <%= f.radio_button :examinee, :false  %>&nbsp;一般</td>
              </tr>
              <tr>
                <th>固定曜日</th>
                <% weekday = [["月"],["火"],["水"],["木"],["金"],["土"],["日"]] %>
                <td><%= f.select :fix_day, weekday, {selected:@student.fix_day}, required: true, class: "form-control new-form" %></td>
              </tr>
              <tr>
                <th>固定開始時間</th>
                <td><%= f.time_field :fix_time , class: "form-control", required: true %></td>
              </tr>
              <tr>
                <th>固定終了時間</th>
                <td><%= f.time_field :fix_finishtime , class: "form-control" %></td>
              </tr>
              
              <tr>
                <th>固定曜日2</th>
                <td><%= f.select :fix_day2, weekday, {selected:@student.fix_day2,include_blank: true}, class: "form-control new-form" %></td>
              </tr>
              <tr>
                <th>固定開始時間2</th>
                <td><%= f.time_field :fix_time2 , class: "form-control" %></td>
              </tr>
               <tr>
                <th>固定終了時間2</th>
                <td><%= f.time_field :fix_finishtime2 , class: "form-control" %></td>
              </tr>
              
              <tr>
                <th>固定曜日3</th>
                <td><%= f.select :fix_day3, weekday, {selected:@student.fix_day3,include_blank: true}, class: "form-control new-form" %></td>
              </tr>
              <tr>
                <th>固定開始時間3</th>
                <td><%= f.time_field :fix_time3 , class: "form-control" %></td>
              </tr>
              <tr>
                <th>固定終了時間3</th>
                <td><%= f.time_field :fix_finishtime3 , class: "form-control" %></td>
              </tr>
              
              <tr>
                <th>固定曜日4</th>
                <td><%= f.select :fix_day4, weekday, {selected:@student.fix_day4,include_blank: true}, class: "form-control new-form" %></td>
              </tr>
              <tr>
                <th>固定開始時間4</th>
                <td><%= f.time_field :fix_time4 , class: "form-control" %></td>
              </tr>
              <tr>
                <th>固定終了時間4</th>
                <td><%= f.time_field :fix_finishtime4 , class: "form-control" %></td>
              </tr>
              
              <tr>
                <th>固定曜日5</th>
                <td><%= f.select :fix_day5, weekday, {selected:@student.fix_day5,include_blank: true}, class: "form-control new-form" %></td>
              </tr>
              <tr>
                <th>固定開始時間5</th>
                <td><%= f.time_field :fix_time5 , class: "form-control" %></td>
              </tr>
              <tr>
                <th>固定終了時間5</th>
                <td><%= f.time_field :fix_finishtime5 , class: "form-control" %></td>
              </tr>
              
              <tr>
                <th>備考</th>
                <td><%= f.text_field :note, class: "form-control" %></td>
              </tr>
              </table>
            <div class="center">
              <%= f.submit "登録", class: "btn btn-primary btn-#{yield(:class_text)}" %>
              <button type="button" class="btn btn-default btn-<%= yield(:class_text) %>" data-dismiss="modal">
                キャンセル
              </button>
              <div id="parent"></div>
            </div>
          <% end %>
      </div>
    </div>
  </div>
</div>
<script>
$("#student_new_form").submit('turbolinks:request-start', function() {
  var fix = $("input[name='student[fix_time]']").val();
  var fixfinish = $("input[name='student[fix_finishtime]']").val();
  var fix2 = $("input[name='student[fix_time2]']").val();
  var fixfinish2 = $("input[name='student[fix_finishtime2]']").val();
  var fix3 = $("input[name='student[fix_time3]']").val();
  var fixfinish3 = $("input[name='student[fix_finishtime3]']").val();
  var fix4 = $("input[name='student[fix_time4]']").val();
  var fixfinish4 = $("input[name='student[fix_finishtime4]']").val();
  var fix5 = $("input[name='student[fix_time5]']").val();
  var fixfinish5 = $("input[name='student[fix_finishtime5]']").val();
  if (fix > fixfinish) {
    $("#parent").text("固定時間の入力に誤りがあります。確認して再登録お願いします。");
    return false;
  }else if (fix2 > fixfinish2) {
    $("#parent").text("固定時間2の入力に誤りがあります。確認して再登録お願いします。");
    return false;
  }else if (fix3 > fixfinish3) {
    $("#parent").text("固定時間3の入力に誤りがあります。確認して再登録お願いします。");
    return false;
  }else if (fix4 > fixfinish4) {
    $("#parent").text("固定時間4の入力に誤りがあります。確認して再登録お願いします。");
    return false;
  }else if (fix5 > fixfinish5) {
    $("#parent").text("固定時間5の入力に誤りがあります。確認して再登録お願いします。");
    return false;
  } else {
    $("#student_new_form").submit();
  }
});
</script>

app/views/students/_students_time.html.erb
<div class="modal fade" id="modal2" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
  <div class="modal-dialog modal-xl">
    <div class="modal-content">
      <div class="modal-header" style="border: none;">
        <button type="button" class="close">
            <span aria-hidden="true"><%= link_to "✖️️", users_path %></span>
        </button>
      </div>
      <div class="modal-body">
        <h2 style="font-size: 25px">固定時間一覧</h2>
      <table  align="center">
      <tr><td style="font-size: 20px">
        <% curent = 11000 %>
        <% @student_ls.each do | week ,time , name, finishtime | %> 
          <%= week %>
          <%= time %>-<%=finishtime %>
          <%= name %><br />
        <% end %>  
        </td></tr>
      </table>
      <br />
      <div class="modal-footer">
          <%= link_to "閉じる", users_path ,class:"btn btn-default" %>
      </div>
    </div>
  </div>
</div>

app/views/students/info_edit.js.erb
$("#info-edit").html("<%= escape_javascript(render 'info_edit') %>");
$("#info-edit").modal("show");

app/views/students/show.erb
<% provide(:title, 'All users') %>

<h1>保護者一覧</h1>

<div class="col-md-10 col-md-offset-1">
  <table class="table table-condensed table-hover" id="table-users">
    <thead>
      <tr>
        <th><%= User.human_attribute_name :name %></th>
        <th>受講生</th>
      </tr>
    </thead>

    <% @students.each do |student| %>
      <tr>
        <td>
          <%= link_to student.student_name, info_edit_student_path(student), remote: true %>

        </td>
      </tr>
    <% end %>
  </table>
</div>