config/routes.rb
Rails.application.routes.draw do
  
  #個人情報保護ページ
  get 'protection_low/index'
  #　レッスン関連
  get 'lessons/weeklyschedule'
  post 'lessons/create', to: 'lessons#create'
  #　ユーザー側予約詳細へ
  post 'reservationusers/useredit', to: 'reservationusers#useredit'
  get 'reservationusers/useredit', to: 'reservationusers#useredit'
  #　ユーザー側予約情報更新
  post 'reservationusers/userupdate', to: 'reservationusers#userupdate'
  get 'reservationusers/reservation_delete', to: 'reservationusers#reservation_delete'
  post 'reservationusers/reservation_change_user', to: 'reservationusers#reservation_change_user'
  post 'reservationusers/reservationnewuser', to: 'reservationusers#reservationnewuser'
  post 'reservationusers/reservation_create'
  # 授業コメント
  post 'lessoncomments/create', to: 'lessoncomments#create'
  # 問い合わせ回答
  post 'answers/create', to: 'answers#create'
  # ユーザー側生徒情報更新
  put 'basic_infos/student_update', to: 'basic_infos#student_update'
  patch 'maneger_students/update', to: 'maneger_students#update'
  #管理者　授業中止
  patch '/lessons/cancellation', to: 'lessons#cancellation'
  get 'sessions/new'
  root :to => 'notices#index'
  get '/signup', to: 'users#new'
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :reservation_logs, only: [:index]
  
  # ログインボタン(管理者、生徒)
  patch 'login', to: 'sessions#admin_login'
  put 'login', to: 'sessions#student_login'
  
  resources :users do
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'edit'
      put 'update'
    end
  end
  delete 'users/:id/delete', to: 'users#destroy'
  
  resources :lessons do
   member do
     put 'update'
     get 'lesson_detail'
     patch 'lesson_detail'
     get 'lesson_discontinuation_fix'
     patch 'lesson_discontinuation_fix'
     get 'add_student'
     patch 'add_student'
     delete 'destroy'
   end
  end
  
  resources :students do
    member do
      get 'info_edit'
      patch 'info_update'
      delete 'destroy'
      get 'create'
    end
    collection do
      post 'create'
    end
  end

  resources :notices
  
  resources :reservations, only: [:update, :destroy]
  
  resources :questions
  
  resources :password_resets, only: [:new, :create, :edit, :update]
end

app/models/user.rb
class User < ApplicationRecord
  require 'date'
  has_many :notices, dependent: :destroy
  has_many :lessons, dependent: :destroy
  has_many :lessoncomments, dependent: :destroy
  has_many :reservations, dependent: :destroy
  has_many :students, dependent: :destroy
  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy
  attr_accessor :remember_token, :reset_token
  
  before_save { self.email = email.downcase }

  validates :guardian, length: { maximum: 50 }
  validates :student, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true    
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  validate :class_hoice
  scope :user_kanaorder , -> { order(guardiankana: :asc)}
  
  def self.maneger_kana_order
   order(admin: "desc").order(guardiankana: "ASC")
  end
  
  # 渡された文字列のハッシュ値を返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  # トークンがダイジェストと一致すればtrueを返します。
  def authenticated?(remember_token)
    # ダイジェストが存在しない場合はfalseを返して終了します。
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  # トークンがダイジェストと一致したらtrueを返す
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end
  
  # ランダムなトークンを返す
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  # パスワード再設定の属性を設定する
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  # パスワード再設定のメールを送信する
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end
  
  def class_hoice
    errors.add(:class_choice, "はどちらか一つ選択してください") if zoom.present? && real.present?
  end
  
  #スコープ契約中の保護者一覧
  def self.undercontract
    where("withdrawal is null")
  end
  #契約先全員へのメール
  def self.sendmail_all_users(  title, content, link )
    undercontracts = self.undercontract
    @send_user = find(1)
    @bcc = ""
    @title = title
    @content = content
    @link = link
    #契約中のユーザー全員にメールを送る
    undercontracts.each do | user |
      @destination_user = find(user.id)
      UserMailer.send_mail( @destination_user, @send_user, @bcc, @title, @content, @link ).deliver_now
    end
    #ユーザーに何を送ったかわかるように管理者にも送る。今はひとりだが将来も考え管理者全員に送る。
    admins = where("admin = ?", true )
    admins.each do | user |
      @destination_user = find(user.id)
      UserMailer.send_mail( @destination_user, @send_user, @bcc, @title, @content, @link ).deliver_now
    end
  end
  
  # パスワード再設定の期限が切れている場合はtrueを返す
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :destroy, :edit_basic_info, :update_basic_info]
  before_action :logged_in_user, only: [:new, :show, :edit, :update, :destroy, :edit_basic_info, :update_basic_info]
  before_action :correct_user, only: [:edit, :update, :index]
  before_action :admin_user, only: [:destroy, :edit_basic_info, :update_basic_info]
  before_action :weekday, only: [:index]
  before_action :day_setting, only: [:index]
  include ApplicationHelper
  
  def index
    @users = User.user_kanaorder.undercontract
    #@admins = User.where(admin:true)
    #@weekday = ["月","火","水","木","金","土","日"]
    if params[:cation] == "2"
      @users = User.maneger_kana_order
      @students = Student.all
    elsif params[:cation] == "3"
      @users = User.order(id: "DESC")
      @students = Student.all
    else
      @users = User.undercontract.user_kanaorder
      @students = Student.under_contact
    end
    #固定時間一覧表作成
    @students_undercontact = Student.under_contact
    @students2= Student.under_contact.order(fix_day:"ASC")
    @student_ls = Array.new()
    (0..6).each do |week_number|
      week_day = @weekday[week_number]
      fixtime = @first_time.to_time-TIMECOL
      while fixtime <= @last_time do
       fixtime2 = fixtime + 1800
	     students_times = @students2.where("(fix_time >= ? and fix_time < ?) and fix_day = ? ",fixtime,fixtime2,week_day)
            .or( @students2.where("(fix_time2 >= ? and  fix_time2 < ?) and fix_day2 = ? ",fixtime,fixtime2,week_day))
            .or( @students2.where("(fix_time3 >= ? and  fix_time3 < ?) and fix_day3 = ? ",fixtime,fixtime2,week_day))
            .or( @students2.where("(fix_time4 >= ? and  fix_time4 < ?) and fix_day4 = ? ",fixtime,fixtime2,week_day))
            .or( @students2.where("(fix_time5 >= ? and  fix_time5 < ?) and fix_day5 = ? ",fixtime,fixtime2,week_day))
        if students_times.count > 0
          students_times.each do |st|
            if st.fix_day==week_day and (st.fix_time >= fixtime and st.fix_time < fixtime2)
              time =  timedisplay(st.fix_time)
              finishtime =  timedisplay(st.fix_finishtime)
              examinee = ""
              zoom = ""
              examinee = " 受験生" if st.examinee?
              zoom = " Zoom" if st.zoom?
              student_name = st.student_name + " (" + Student.gradeyear( st.id ) + examinee + zoom + ")" 
              @student_ls.push([st.fix_day,time, student_name,finishtime])
            elsif st.fix_day2==week_day and (st.fix_time2 >= fixtime and st.fix_time2 < fixtime2)
              time =  timedisplay(st.fix_time2)
              finishtime =  timedisplay(st.fix_finishtime2)
              examinee = ""
              zoom = ""
              examinee = " 受験生" if st.examinee?
              zoom = " Zoom" if st.zoom?
              student_name = st.student_name + " (" + Student.gradeyear( st.id ) + examinee + zoom + ")" 
              @student_ls.push([st.fix_day2,time, student_name,finishtime])
            elsif st.fix_day3==week_day and (st.fix_time3 >= fixtime and st.fix_time3 < fixtime2)
              time =  timedisplay(st.fix_time3)
              finishtime =  timedisplay(st.fix_finishtime3)
              examinee = ""
              zoom = ""
              examinee = " 受験生" if st.examinee?
              zoom = " Zoom" if st.zoom?
              student_name = st.student_name + " (" + Student.gradeyear( st.id ) + examinee + zoom + ")" 
              @student_ls.push([st.fix_day3,time, student_name,finishtime])
            elsif st.fix_day4==week_day and (st.fix_time4 >= fixtime and st.fix_time4 < fixtime2)
              time =  timedisplay(st.fix_time4)
              finishtime =  timedisplay(st.fix_finishtime4)
              examinee = ""
              zoom = ""
              examinee = " 受験生" if st.examinee?
              zoom = " Zoom" if st.zoom?
              student_name = st.student_name + " (" + Student.gradeyear( st.id ) + examinee + zoom + ")" 
              @student_ls.push([st.fix_day4,time, student_name,finishtime])
            elsif st.fix_day5==week_day and (st.fix_time5 >= fixtime and st.fix_time5 < fixtime2)
              time =  timedisplay(st.fix_time5)
              finishtime =  timedisplay(st.fix_finishtime5)
              examinee = ""
              zoom = ""
              examinee = " 受験生" if st.examinee?
              zoom = " Zoom" if st.zoom?
              student_name = st.student_name + " (" + Student.gradeyear( st.id ) + examinee + zoom + ")" 
              @student_ls.push([st.fix_day5,time, student_name,finishtime])
            end
          end
        end
	      fixtime = fixtime + 1800
	    end
    end
  end
   
   
  def new
    @user = User.new
    @student = Student.new
  end
  
  def show
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = '新規作成に成功しました。確認をお願いします。'
      redirect_to '/users?cation=3'
    else
      render :new
    end
  end
  def edit
    
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "情報を更新しました。"
      redirect_to '/users'
    else
      render :edit      
    end
    @user = User.find(params[:id])
  end
  
  def destroy
    if @user.destroy
      flash[:success] = "#{@user.guardian}のデータを削除しました。"
    else
      flash[:danger] = "#{@user.guardian}のデータ削除に失敗しました。"
    end
    redirect_to users_url
  end
  
  def edit_basic_info
    
  end
  
  def update_basic_info
    if @user.update_attributes(user_params)
      flash[:success] = "#{@user.guardian}の基本情報を更新しました。"
    else
      flash[:danger] = "#{@user.guardian}の更新は失敗しました。メールアドレスの重複等確認願います。" 
    end
    redirect_to users_url
  end
  
  def login_page
  end
  
  private
    def user_params
      params.require(:user).permit(:guardian, :guardiankana,:student, :email,  :password, :password_confirmation, :withdrawal, :admin)
    end
    
    # beforeフィルター

    # ログイン済みのユーザーか確認します。
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "ログインしてください。"
        redirect_to login_url
      end
    end
    
    # アクセスしたユーザーが現在ログインしているユーザーか確認します。
    def correct_user
      if current_user.admin == false
        redirect_to(root_url) unless current_user?(@user)
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_edit_basic_info.html.erb
<% provide(:class_text, 'basic-info') %>
<% provide(:button_text, '更新') %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <h1 class="modal-title">ユーザー情報編集</h1>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <%= form_with(model: @user, url: update_basic_info_user_path(@user), local: true, method: :patch) do |f| %>
            <%= render 'shared/error_messages', object: @user %>

            <%= f.label :保護者, class: "label-#{yield(:class_text)}" %>
            <p><%= f.text_field :guardian, class: "form-control", required: true %></p>

            <%= f.label :保護者カナ, class: "label-#{yield(:class_text)}" %>
            <p><%= f.text_field :guardiankana, class: "form-control", required: true %></p>
            
            <%= f.label :email, class: "label-#{yield(:class_text)}" %>
            <%= f.email_field :email, class: "form-control", required: true %>

            <%= f.label :password, class: "label-#{yield(:class_text)}" %>
            <%= f.password_field :password, class: "form-control" %>

            <%= f.label :退会日（全受講生が退会すれば自動登録されます）, class: "label-#{yield(:class_text)}" %>
            <%= f.date_field :withdrawal, class: "form-control" %>
            <br />
            <%= f.check_box :admin  %>&nbsp;<%= f.label :管理者, class: "label-#{yield(:class_text)}" %>
            
            <!--電話番号のカラムが必要と思われるので実装予定-->

            <div class="center">
              <%= f.submit yield(:button_text), class: "btn btn-primary btn-#{yield(:class_text)}" %>
              <button type="button" class="btn btn-default btn-<%= yield(:class_text) %>" data-dismiss="modal">
                キャンセル
              </button>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_new_basic_info.html.erb
<div class="modal fade" id=<%= @user_id %> tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content" margin:auto;"=" margin:auto;""="margin:auto;""">
      <div class="modal-body">
      <h2>受講生新規登録</h2>
      保護者：<%= User.find(@user_id).guardian %>
      <% @student = Student.new %>
       <%= form_with(model: @student, url: students_path, local: true, method: :post) do |f| %>
            <table class="table-student">
            <%= f.hidden_field :user_id ,value: @user_id %>
              <tr>
                <th>生徒名</th>
                <td><%= f.text_field :student_name , class: "form-control", required: true %></td>
              </tr>
              <tr>
                <th>生徒カナ</th>
                <td><%= f.text_field :studentkana ,  class: "form-control", required: true %></td>
              </tr>
              <tr>
                <th>生年月日</th>
                <td><%= f.date_field :birthday, class: "form-control", required: true %></td>
              </tr>
              <tr>
                <th>学校名</th>
                <td><%= f.text_field :school, class: "form-control" %></td>
              </tr>
              <tr>
                <th>受講方法</th>
                <td style = "text-align:left; font-size:15px; margin-left:10px;">
                &nbsp;<%= f.radio_button :zoom, :false %>&nbsp;リアル
                <%= f.radio_button :zoom, :true  %>&nbsp;Zoom</td>
              </tr>
              <tr>
                <th>受験生区分</th>
                <td style = "text-align:left; font-size:15px; margin-left:10px;">
                &nbsp;<%= f.radio_button :examinee, :true %>&nbsp;受験生
                <%= f.radio_button :examinee, :false  %>&nbsp;一般</td>
              </tr>
              <tr>
                <th>固定曜日</th>
                <% weekday = [["月"],["火"],["水"],["木"],["金"],["土"],["日"]] %>
                <td><%= f.select :fix_day, weekday, {selected:@student.fix_day}, required: true, class: "form-control new-form" %></td>
              </tr>
              <tr>
                <th>固定時間</th>
                <td><%= f.time_field :fix_time , class: "form-control", required: true %></td>
              </tr>
              <tr>
                <th>固定曜日2</th>
                <td><%= f.select :fix_day2, weekday, {selected:@student.fix_day2,include_blank: true}, class: "form-control new-form" %></td>
              </tr>
              <tr>
                <th>固定時間2</th>
                <td><%= f.time_field :fix_time2 , class: "form-control" %></td>
              </tr>
              <tr>
                <th>固定曜日3</th>
                <td><%= f.select :fix_day3, weekday, {selected:@student.fix_day3,include_blank: true}, class: "form-control new-form" %></td>
              </tr>
              <tr>
                <th>固定時間3</th>
                <td><%= f.time_field :fix_time3 , class: "form-control" %></td>
              </tr>
              <tr>
                <th>備考</th>
                <td><%= f.text_field :note, class: "form-control" %></td>
              </tr>
              </table>
            <div class="center">
              <%= f.submit "登録", class: "btn btn-primary btn-#{yield(:class_text)}" %>
              <button type="button" class="btn btn-default btn-<%= yield(:class_text) %>" data-dismiss="modal">
                キャンセル
              </button>
            </div>
          <% end %>
      
        
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<% provide(:title, "編集") %>
<h1>保護者情報編集</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user, local: true, method: :put) do |f| %>
    
      ・<%= f.label :保護者名前, class: "label-signup" %>
      <span class="label label-danger label-user-division">必須</span>
      <%= f.text_field :guardian, required: true, class: "form-control" %>

      ・<%= f.label :保護者カナ, class: "label-signup" %>
      <span class="label label-danger label-user-division">必須</span>
      <%= f.text_field :guardiankana, required: true, class: "form-control" %>

     <!--メールアドレス-->
      ・<%= f.label :email, class: "label-signup" %>
      <span class="label label-danger label-user-division">必須</span>
      <%= f.email_field :email, required: true, class: "form-control" %>
      
     <!--パスワード-->
      ・<%= f.label :password, class: "label-signup" %> 
      <%= f.password_field :password, class: "form-control" %>
      
      <!--パスワード再入力-->
      ・<%= f.label :password_confirmation, class: "label-signup" %> 
      <%= f.password_field :password_confirmation, class: "form-control" %>

      <%= f.submit "更新", class: "btn btn-primary btn-block btn-user--edit" %>
    <% end %>
    <br />
    <div style="text-align:center"><a href="#" onclick="javascript:window.history.back(-1);return false;">前のページに戻る</a></div>
  </div>
</div>

app/views/users/edit_basic_info.js.erb
$("#edit-basic-info").html("<%= escape_javascript(render 'edit_basic_info') %>");
$("#edit-basic-info").modal("show");

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h2 style="font-size:30px;">契約一覧</h2>

<div class="wrapper_middle">
  <div style="display: inline-block;"><%= button_to "契約者", {controller: 'users', action: 'index'}, {method: :get, params: {cation:"1"}} %></div>
  <div style="display: inline-block;"><%= button_to "全表示", {controller: 'users', action: 'index'}, {method: :get, params: {cation:"2"}} %></div>
  <div style="display: inline-block;"><%= button_to "登録順", {controller: 'users', action: 'index'}, {method: :get, params: {cation:"3"}} %></div>
  <a href="" data-toggle="modal" data-target=#modal2>固定時間一覧</a>
   <%= render partial: "/students/students_time" %>
</div><br /><br />
  
  <table class="table table-condensed table-hover" id="table-users">
    <thead>
      <tr>
        <th><%= User.human_attribute_name :guardian %><%= link_to "新規登録", signup_path %></th>
        <th></th>
        <th>受講生</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <% @users.each do |user| %>
      <tr>
        <td>
          <%= link_to user.guardian, edit_basic_info_user_path(user), remote: true %>
          <% if user.admin %>
          <span class="label label-primary label-user-division">管理者</span>
          <% end %>
          <% students = @students.where(user_id: user.id) %>
         </td>
         <td>
         <%= link_to "削除","users/#{user.id}/delete", method: :delete, 
              data:  { confirm: "本当に削除してよろしいですか？該当の受講生、予約授業も併せて削除します"},
              class: "btn btn-danger btn-sm" %>
          <% students = @students.where(user_id: user.id) %>
        </td>
        <td>
          <% students.each do |student| %>
           <%= link_to student.student_name, info_edit_student_path(student), remote: true %> 
            <% if students.count >0 %>  
            (<%= Student.gradeyear(student.id) %> <%= student.school %>)
                固定時間:<%= student.fix_day %> <%= timedisplay(student.fix_time) %>&nbsp;
            <% end %>
            <% if student.fix_day2.present? %>
                <%= student.fix_day2 %> <%= timedisplay(student.fix_time2) %>&nbsp;
            <% end %>
            <% if student.fix_day3.present? %>
                <%= student.fix_day3 %> <%= timedisplay(student.fix_time3) %>&nbsp; 
            <% end %>
            <% if student.fix_day4.present? %>
                <%= student.fix_day4 %> <%= timedisplay(student.fix_time4) %>&nbsp;
            <% end %>
            <% if student.fix_day5.present? %>
                <%= student.fix_day5 %> <%= timedisplay(student.fix_time5) %>&nbsp; 
            <% end %>
            <% if student.zoom?  %>
              <span class="label label-warning label-user-division">zoom</span>
            <% end %>
            <% if student.examinee? %>
                <span class="label label-success label-user-division">受験生</span>
            <% end %>
            <% if student.withdrawal.present? %>
                <span class="label label-danger label-user-division">退会</span>
            <% end %>
            <% if students.count >1 %>
              <br>
            <% end %>
           <% end %>
        </td> 
        <td>
          <% @user_id = user.id %>
          <a href="" data-toggle="modal" data-target=#<%= @user_id %> class="btn btn-primary btn-sm pull-right">受講生新規</a>
            <!--生徒新規モーダル -->
          <%= render partial: "/students/new_basic_info" %>
        </td>
      </tr>
    <% end %> 
    <tr><td></td><td></td><td></td><td></td></tr>
  </table>
  </div>


<!--モーダルウインドウ表示-->
<div id="edit-basic-info" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="info-edit" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
 

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, '新規登録') %>
<h1>保護者登録</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'shared/error_messages' %>
      
      <!--保護者名-->
      ・<%= f.label :guardian, class: "label-signup" %>
      <span class="label label-danger label-user-division">必須</span>
      <%= f.text_field :guardian, required: true, class: "form-control new-form" %>

      <!--保護者名-->
      ・<%= f.label :保護者カナ, class: "label-signup" %>
      <span class="label label-danger label-user-division">必須</span>
      <%= f.text_field :guardiankana, required: true, class: "form-control new-form" %>

      <!--メールアドレス-->
      ・<%= f.label :email, class: "label-signup" %>
      <span class="label label-danger label-user-division">必須</span>
      <%= f.email_field :email, required: true, class: "form-control new-form" %>
      
     <!--パスワード-->
      ・<%= f.label :password, class: "label-signup" %> 
      <span class="label label-danger label-user-division">必須</span>
      <%= f.password_field :password, required: true, class: "form-control new-form" %>
      
      <!--パスワード再入力-->
      ・<%= f.label :password_confirmation, class: "label-signup" %> 
      <span class="label label-danger label-user-division">必須</span>
      <%= f.password_field :password_confirmation, required: true, class: "form-control new-form" %>

      <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-signup" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.student) %>
<ul>
  <li>保護者名:<%= @user.guardian %></li>
  <li>メールアドレス:<%= @user.email %></li>
</ul>